### PR TITLE
fix: posgres port and default values

### PR DESCRIPTION
**Pull request by SkeLLLa**
## Proposed changes

Align with actual code that's used in deployment https://github.com/WeblateOrg/helm/blob/main/charts/weblate/templates/deployment.yaml#L60

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added documentation to describe my feature.
- [x] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

### CODE REVIEW

**Comment by nijel** [comment]
This was changed to align with PostgreSQL upgrade in https://github.com/WeblateOrg/helm/commit/1c85b0833cafeb275f2b301ce7414fad741928b6 by @gllb

**Comment by SkeLLLa** [comment]
@nijel then it doesn't work as expected, since it's not used in [deployment](https://github.com/WeblateOrg/helm/blob/main/charts/weblate/templates/deployment.yaml#L60).

**Comment by SkeLLLa** [comment]
Added alternative PR. Feel free to choose one that suites best.

**Comment by nijel** [comment]
The problem with this repo is that it is merely driven by one-off contributions. People address the issue they have without considering other use-cases. I have no clue which of https://github.com/WeblateOrg/helm/pull/368 and https://github.com/WeblateOrg/helm/pull/367 are better approaches here.

**Comment by SkeLLLa** [comment]
@nijel I think #368 in this case might be better, since it doesn't affect user config, just fixes the deployment. And it also preserves changes made by @gllb.
And current state of repo it's impossible to have postgres DB on any other port, rather than default `5432`.

**Comment by nijel** [comment]
Okay, let's go with that for now.

**Pull request closed without merging**
