### PR TITLE
Support for extra secret variables

### PR DESCRIPTION
**Pull request by Yann-J**
## Proposed changes

This PR implements a few Helm chart improvements:

* Support for extra environment variables to be passed as Kubernetes `Secret` (so they can be referenced in `settings-override.py` with `os.environ`)
* For all environment variables (Secret or not), support for multiline values and evaluating as Helm templates (so can include {{}} placeholders)
* Support for Namespaces

## Checklist

- [ ] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added documentation to describe my feature.
- [ ] I have squashed my commits into logic units.
- [ ] I have described the changes in the commit messages.

### CODE REVIEW

**Review by tarioch — COMMENTED** [review]
Looks good, please take a note of the failing checks (e.g. Chart Bump) and then I think it can get merged

**Comment by Yann-J** [comment]
Ah yes good catch... Fixed!

However I'm not sure what the other check failure is about (in the doc generation step)... any thoughts @tarioch ?

**Comment by tarioch** [comment]
The readme does not match the values file. Easiest is to run helm docs by hand, this will update the readme and you can check it in.

**Comment by Yann-J** [comment]
OK, finally got it to work now @tarioch thanks!
Very nice CI setup you have there btw!

**Pull request merged**
